"use client";

import {
  type ComponentProps,
  type HTMLAttributes,
  type ReactNode,
  type RefObject,
  useMemo,
  useRef
} from "react";

import { mergeRefs } from "@rzl-zone/core-react/utils";

import { cn } from "@rzl-zone/docs-ui/utils";
import { buttonVariants } from "@rzl-zone/docs-ui/components/cva";
import { CheckSquare, Copy } from "@rzl-zone/docs-ui/components/icons/lucide";

import { ScrollArea } from "@rzl-zone/docs-ui/components/scroll-area";
import { Transition } from "@rzl-zone/docs-ui/components/headless-ui-react";

import { useCopyButtonFD } from "@/hooks/use-copy-button-fd";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import { createRequiredContext } from "@rzl-zone/core-react/context";
import { Button } from "@rzl-zone/docs-ui/components/button";

export interface CodeBlockProps extends ComponentProps<"figure"> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode | "disable";

  /**
   * Disable showing Icon ?
   *
   * @default false
   */
  noIcon?: boolean;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;

  /**
   * Disables the forced `tabIndex` behavior on the element.
   *
   * By default, the component may automatically assign a `tabIndex`
   * to ensure proper focus management and accessibility. Enabling
   * this option will prevent that behavior.
   *
   * @default false
   */
  disableForceUnTabIndex?: boolean;
}

const TabsContext = createRequiredContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>("TabsContext", null);

export function Pre(props: ComponentProps<"pre">) {
  // console.debug({ a: isReactNode(props.children) });

  return (
    <pre
      {...props}
      className={cn("min-w-full w-max *:flex *:flex-col", props.className)}
    >
      {props.children}
    </pre>
  );
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  noIcon = false,
  viewportProps = {},
  children,
  Actions = (props) => (
    <div
      {...props}
      className={cn("empty:hidden", props.className)}
    />
  ),
  disableForceUnTabIndex = false,
  ...props
}: CodeBlockProps) {
  const inTab = TabsContext.use() !== null;
  const areaRef = useRef<HTMLDivElement>(null);

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={disableForceUnTabIndex ? (props.tabIndex ?? -1) : -1}
      className={cn(
        inTab
          ? "bg-fd-card -mx-px -mb-px rounded-b-xl"
          : "mB-2 mt-2.5 bg-fd-card rounded-xl",
        keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",
        !inTab && "shadow-md",
        "shiki relative border outline-none not-prose text-sm",
        props.className
      )}
    >
      <>
        {title ? (
          <div className="bg-fd-secondary flex text-fd-foreground/60 items-center gap-2 h-9.5 border-b px-4 font-medium rounded-t-xl">
            {!noIcon &&
              (typeof icon === "string" ? (
                <div
                  className={cn(inTab ? "[&_svg]:size-4" : "[&_svg]:size-3.5")}
                  dangerouslySetInnerHTML={{
                    __html: icon
                  }}
                />
              ) : (
                icon
              ))}
            <figcaption className="flex-1 truncate">{title}</figcaption>
            {Actions({
              className:
                "top-11.5 absolute right-2 z-4 backdrop-blur-md rounded-md bg-fd-card p-px",
              children: allowCopy && <CopyButton containerRef={areaRef} />
            })}
          </div>
        ) : (
          Actions({
            className:
              "top-2 absolute right-2 z-4 backdrop-blur-md rounded-md p-0.5",
            children: allowCopy && <CopyButton containerRef={areaRef} />
          })
        )}

        <ScrollArea
          scrollHideDelay={10}
          className={inTab || title ? "rounded-b-xl" : "rounded-xl"}
          viewPortOptions={{
            ...viewportProps,
            tabIndex: props.tabIndex ?? -1,
            ref: areaRef,
            className: cn("text-sm py-3 max-h-150", viewportProps.className),
            style: {
              // space for toolbar
              "--padding-right": !title
                ? "calc(var(--spacing) * 8)"
                : undefined,
              counterSet: props["data-line-numbers"]
                ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
                : undefined,
              ...viewportProps.style
            } as object
          }}
          scrollBarOptions={{ orientation: "all" }}
          tabIndex={-1}
        >
          {children}
        </ScrollArea>
      </>
    </figure>
  );
}

function CopyButton({
  className,
  containerRef,
  ...props
}: ComponentProps<"button"> & {
  containerRef: RefObject<HTMLElement | null>;
}) {
  const [checked, onClick] = useCopyButtonFD({
    onCopy: () => {
      const pre = containerRef.current?.getElementsByTagName("pre").item(0);
      if (!pre) return;

      const clone = pre.cloneNode(true) as HTMLElement;
      clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
        node.replaceWith("\n");
      });

      void navigator.clipboard.writeText(clone.textContent ?? "");
    }
  });

  return (
    <Button
      type="button"
      data-checked={checked || undefined}
      className={cn(
        buttonVariants({
          variant: "ghost",
          className: cn(
            "flex flex-row flex-1 gap-1 hover:text-fd-accent-foreground data-checked:text-fd-accent-foreground",
            "transform transition-colors duration-300 p-0"
          ),
          size: "icon-xs"
        }),
        className
      )}
      aria-label={checked ? "Copied to clipboard" : "Copy to clipboard"}
      onClick={onClick}
      {...props}
      tabIndex={props.tabIndex ?? -1}
    >
      <div className="relative size-6 min-w-6 min-h-6">
        <Transition
          show={!checked}
          enter="transition-all duration-300 ease-out"
          enterFrom="opacity-0 scale-75"
          enterTo="opacity-100 scale-100"
          leave="transition-all duration-300 ease-in"
          leaveFrom="opacity-100 scale-100"
          leaveTo="opacity-0 scale-75"
        >
          <div className="absolute inset-0 flex items-center justify-center">
            <Copy />
            <span className="sr-only">Copy</span>
          </div>
        </Transition>

        <Transition
          show={checked}
          enter="transition-all duration-300 ease-out"
          enterFrom="opacity-0 scale-75"
          enterTo="opacity-100 scale-100"
          leave="transition-all duration-300 ease-in"
          leaveFrom="opacity-100 scale-100"
          leaveTo="opacity-0 scale-75"
        >
          <div className="absolute inset-0 flex items-center justify-center">
            <CheckSquare />
            <span className="sr-only">Copied!</span>
          </div>
        </Transition>
      </div>
    </Button>
  );
}

export function CodeBlockTabs({ ref, ...props }: ComponentProps<typeof Tabs>) {
  const containerRef = useRef<HTMLDivElement>(null);
  const nested = TabsContext.use() !== null;

  return (
    <Tabs
      ref={mergeRefs(containerRef, ref)}
      {...props}
      className={cn(
        "[&>div]:first:bg-fd-secondary [&>div]:first:rounded-t-xl [&>div]:first:shadow-md [&>div]:first:border [&>div>figure:only-child]:shadow-md",
        !nested &&
          "my-2 [&>div>figure:only-child]:mt-0 [&>div>figure:only-child]:bg-fd-card [&>div>figure:only-child]:mx-0 [&>div>figure:only-child]:border [&>div>figure:only-child]:border-t-0",
        props.className
      )}
      tabIndex={props.tabIndex ?? -1}
    >
      <TabsContext.Provider
        value={useMemo(
          () => ({
            containerRef,
            nested
          }),
          [nested]
        )}
      >
        {props.children}
      </TabsContext.Provider>
    </Tabs>
  );
}

export function CodeBlockTabsList(props: ComponentProps<typeof TabsList>) {
  return (
    <TabsList
      {...props}
      className={cn(
        "flex flex-row px-2 overflow-x-auto text-fd-muted-foreground",
        props.className
      )}
      tabIndex={props.tabIndex ?? -1}
    >
      {props.children}
    </TabsList>
  );
}

export function CodeBlockTabsTrigger({
  children,
  ...props
}: ComponentProps<typeof TabsTrigger>) {
  return (
    <TabsTrigger
      {...props}
      tabIndex={props.tabIndex ?? -1}
      className={cn(
        "relative group inline-flex text-sm font-medium text-nowrap items-center transition-colors gap-2 px-2 py-1.5 hover:text-fd-accent-foreground data-[state=active]:text-fd-primary [&_svg]:size-4",
        props.className
      )}
    >
      <div className="absolute inset-x-2 bottom-0 h-px group-data-[state=active]:bg-fd-primary" />
      {children}
    </TabsTrigger>
  );
}

export function CodeBlockTab(props: ComponentProps<typeof TabsContent>) {
  return (
    <TabsContent
      {...props}
      tabIndex={props.tabIndex ?? -1}
    />
  );
}
