import { isNonEmptyString } from "@/_internal/utils/helper";
import { ConfigurationError, picocolors } from "@/utils/client";

/** ----------------------------------------------------------------
 * * Styles a Commander-generated usage string.
 * ----------------------------------------------------------------
 *
 * Applies color formatting to tokens produced by the default
 * Commander `.usage()` output.
 *
 * The input string is tokenized by whitespace and each segment
 * is conditionally styled based on its semantic role.
 *
 * Styling rules:
 *
 * - The first token (typically the command name) is highlighted
 *   when `fromHelpCommandUsage` is enabled.
 * - `[options]` tokens are styled to indicate optional flags.
 * - `[command]` tokens are styled to indicate subcommands.
 * - Required arguments (`<arg>`) are dimmed.
 * - Optional arguments (`[arg]`) are dimmed.
 *
 * Tokens that do not match any rule are returned unchanged.
 *
 * ----------------------------------------------------------------
 * @param raw - The raw usage string generated by Commander.
 *
 * @param options - Optional formatting configuration.
 *
 * @param options.fromHelpCommandUsage
 * If `true`, the first token will be highlighted to represent
 * the command name in help output.
 *
 * @param options.errorConfig
 * Optional configuration used when constructing a
 * {@link ConfigurationError} if validation fails.
 *
 * ----------------------------------------------------------------
 * @returns The styled usage string with ANSI color formatting.
 *
 * @throws {ConfigurationError}
 * Thrown when `raw` is not a non-empty string.
 *
 * @internal
 */
export function styleUsage(
  raw: string,
  {
    fromHelpCommandUsage,
    errorConfig: {
      field = "raw",
      expected = "a non-empty string",
      context = "styleUsage"
    } = {}
  }: {
    /** @default false */
    fromHelpCommandUsage?: true;
    errorConfig?: {
      /** @default "raw" */
      field?: string;
      /** @default "a non-empty string" */
      expected?: string;
      /** @default "styleUsage" */
      context?: string;
    };
  } = {}
) {
  if (!isNonEmptyString(raw)) {
    throw ConfigurationError.type(field, expected, raw, context);
  }

  return raw
    .split(/\s+/)
    .map((token, index) => {
      if (!!fromHelpCommandUsage && index === 0) {
        return picocolors.cyanBright(token);
      }

      if (token === "[options]") {
        return picocolors.blueBright(token);
      }

      if (token === "[command]") {
        return picocolors.magentaBright(token);
      }

      if (token.startsWith("<") && token.endsWith(">")) {
        return picocolors.gray(token);
      }

      if (token.startsWith("[") && token.endsWith("]")) {
        return picocolors.gray(token);
      }

      return token;
    })
    .join(" ");
}

/** ----------------------------------------------------------------
 * * Normalizes Commander usage token order.
 * ----------------------------------------------------------------
 *
 * Reorders usage tokens so that the `[options]` segment
 * always appears **at the end of the usage string**.
 *
 * Commander may sometimes place `[options]` before other
 * tokens such as arguments or subcommands. This function
 * ensures a consistent ordering for CLI help output.
 *
 * Example:
 *
 * ```
 * input:  "cli [options] <file>"
 * output: "cli <file> [options]"
 * ```
 *
 * The function preserves the relative ordering of all
 * non-option tokens.
 *
 * ----------------------------------------------------------------
 * @param raw - The raw usage string generated by Commander.
 *
 * @param options - Optional validation configuration.
 *
 * @param options.errorConfig
 * Configuration used when constructing a
 * {@link ConfigurationError} if validation fails.
 *
 * ----------------------------------------------------------------
 * @returns The normalized usage string with `[options]`
 * positioned at the end.
 *
 * @throws {ConfigurationError}
 * Thrown when `raw` is not a non-empty string.
 *
 * @internal
 */
export function reorderUsage(
  raw: string,
  {
    errorConfig: {
      field = "raw",
      expected = "a non-empty string",
      context = "reorderUsage"
    } = {}
  }: {
    errorConfig?: {
      /** @default "raw" */
      field?: string;
      /** @default "a non-empty string" */
      expected?: string;
      /** @default "reorderUsage" */
      context?: string;
    };
  } = {}
) {
  if (!isNonEmptyString(raw)) {
    throw ConfigurationError.type(field, expected, raw, context);
  }

  const tokens = raw.match(/\S+/g) ?? []; //raw.split(/\s+/);

  const optionTokens = tokens.filter((t) => t === "[options]");
  const otherTokens = tokens.filter((t) => t !== "[options]");

  return [...otherTokens, ...optionTokens].join(" ");
}
