import fs from "node:fs";
import path from "node:path";
import semver from "semver";

import { isString } from "@rzl-zone/utils-js/predicates";
import { normalizePathname } from "@rzl-zone/utils-js/urls";

import { ensureParentDir } from "@rzl-zone/core/node/fs";

import { type CachedDoc } from "@/utils/fumadocs/types";
import { getPackageData } from "@/utils/packages/docs";
import { SOURCE_CONFIG } from "@/configs/source/package";

function getFoldersSync({
  folderName = "",
  dirContent = normalizePathname(SOURCE_CONFIG.DOCS.DEFINE_DOCS.DIR),
  sortDecs = false,
  isRoot = false
}: {
  /**
   * @default ""
   */
  folderName?: string | undefined | null;
  /**
   * @default SOURCE_CONFIG.DOCS.DEFINE_DOCS.DIR
   */
  dirContent?: string;
  /**
   * @default false
   */
  sortDecs?: boolean;
  /**
   * @default false
   */
  isRoot?: boolean;
} = {}): string[] {
  if (!isString(folderName) || !isString(dirContent.trim())) return [];

  folderName = folderName.trim();
  dirContent = dirContent.trim();

  const basePath = path.join(process.cwd(), dirContent, folderName);
  if (!fs.existsSync(basePath)) return [];

  const entries = fs.readdirSync(basePath, { withFileTypes: true });
  const results: string[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    if (entry.name.startsWith("_")) continue;

    if (isRoot) {
      // ROOT: Take all of package
      results.push(entry.name);
      continue;
    }

    if (/^\(latest\)$/.test(entry.name)) {
      results.push("latest");
      continue;
    }

    if (/^\((.*)\)$/.test(entry.name)) {
      const children = getFoldersSync({
        folderName: entry.name,
        dirContent: path.join(dirContent, folderName)
      });
      results.push(...children);

      // const match = entry.name.match(/^\((.*)\)$/);
      // const groupName = match?.[1];
      // if (groupName && _isValidVersionFolder(groupName)) {
      //   results.push(groupName);
      // }
      // const children = getFoldersSync({
      //   folderName: entry.name,
      //   dirContent: path.join(dirContent, folderName)
      // });
      // results.push(...children);
      // continue;
    }

    // FILTER ONLY NOT ROOT
    if (!_isValidVersionFolder(entry.name)) {
      continue;
    }

    results.push(entry.name);
  }

  if (sortDecs) {
    results.sort((a, b) => b.localeCompare(a, undefined, { numeric: true }));
  } else {
    results.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  }

  return results;
}

function _getLatestVersionSync({
  folderName,
  dirContent = normalizePathname(SOURCE_CONFIG.DOCS.DEFINE_DOCS.DIR)
}: {
  folderName: string | undefined | null;
  dirContent?: string;
}): string | null {
  const versions = getFoldersSync({ folderName, dirContent });
  if (versions.length === 0) return null;
  if (versions.includes("latest")) return "latest";
  const validVersions = versions.filter((v) => semver.valid(v));
  if (validVersions.length === 0) return null;
  return semver.sort(validVersions).pop() ?? null;
}

function buildDocsCache() {
  const packageNames = getFoldersSync({ isRoot: true });

  const results = packageNames.map(
    (pkg) =>
      ({
        key: pkg,
        slug: pkg,
        name: getPackageData(pkg)?.name || null,
        description: getPackageData(pkg)?.description || null,
        versions: getFoldersSync({ folderName: pkg, sortDecs: true }),
        // latest: _getLatestVersionSync({ folderName: pkg }),
        githubUrl: getPackageData(pkg)?.githubUrl,
        actualVersionLatest: getPackageData(pkg)?.actualVersionLatest || {}
      }) satisfies CachedDoc
  );

  // Path (ts)
  const outputPath = path.join(process.cwd(), "data/cache/docs-package.ts");
  ensureParentDir(outputPath);

  const tsContent = `
/** ----------------------------------------------------
 * * ***DO NOT EDIT MANUALLY !!!***
 * ----------------------------------------------------
 * ***Auto-generated by \`generate-docs-cache.ts\` or \`npm run generate:docs-cache\`.***
 */
export const cacheDocsPackage = ${JSON.stringify(results, null, 2)};
`;

  fs.writeFileSync(outputPath, tsContent);

  console.log("✅ Docs cache generated:");
  console.log("   ➤ ", outputPath);
}

const _isValidVersionFolder = (name: string) => {
  if (name === "latest") return true;

  // semver (1.0.0, 1.0.0-beta.1)
  if (semver.valid(name)) return true;

  // major (2.x, v2)
  if (/^v?\d+(?:\.x)?$/.test(name)) return true;

  // channel (beta, rc, dll)
  if (["alpha", "beta", "rc", "dev", "canary"].includes(name)) return true;

  return false;
};

buildDocsCache();
