import "dotenv/config";

import fs from "fs";
import path from "path";
import matter from "gray-matter";
import z, { ZodError } from "zod";

import { normalizePathname } from "@rzl-zone/utils-js/urls";

import { ensureParentDir } from "@rzl-zone/core/node/fs";

import { env } from "@/utils/env";
import { generatePageData } from "@/utils/meta-data";
import { pageSchema } from "@/configs/source/schema";
import { SOURCE_CONFIG } from "@/configs/source/package";
import type { CachedJsonLD } from "@/utils/fumadocs/types";

const BASE_URL = env.NEXT_PUBLIC_BASE_URL;
const DOCS_DATA = path.join(
  process.cwd(),
  normalizePathname(SOURCE_CONFIG.DOCS.DEFINE_DOCS.DIR).replace(/^\/+/, "")
);

type PageData = {
  url: string;
  og: { imageUrl: string };
  pageData: ReturnType<typeof generatePageData>;
};

/** Recursively collect all docs pages
 * - Skips hidden files/folders (starts with '.')
 * - Skips App Router group folders (starts with '(') in URL
 * - Converts `index.mdx` to root of folder
 * - Parses frontmatter for title & description
 */
function getAllDocsPages(dir: string, parentPath = ""): PageData[] {
  const pages: PageData[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue; // skip hidden

    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      const isGroup = /^\(.*\)$/.test(entry.name);
      const newParentPath = isGroup
        ? parentPath
        : parentPath
          ? `${parentPath}/${entry.name}`
          : entry.name;

      pages.push(...getAllDocsPages(fullPath, newParentPath));
    } else if (entry.isFile() && entry.name.endsWith(".mdx")) {
      const fileName = entry.name.replace(".mdx", "");
      const urlPath =
        fileName === "index"
          ? parentPath
            ? `/${SOURCE_CONFIG.LOADER.BASE_URL}/${parentPath}`
            : `/${SOURCE_CONFIG.LOADER.BASE_URL}`
          : parentPath
            ? `/${SOURCE_CONFIG.LOADER.BASE_URL}/${parentPath}/${fileName}`
            : `/${SOURCE_CONFIG.LOADER.BASE_URL}/${fileName}`;

      const urlOgImage =
        fileName === "index"
          ? parentPath
            ? `/${SOURCE_CONFIG.LOADER.OG.IMAGE_URL}/${parentPath}`
            : `/${SOURCE_CONFIG.LOADER.OG.IMAGE_URL}`
          : parentPath
            ? `/${SOURCE_CONFIG.LOADER.OG.IMAGE_URL}/${parentPath}/${fileName}`
            : `/${SOURCE_CONFIG.LOADER.OG.IMAGE_URL}/${fileName}`;

      // Parse frontmatter with gray-matter
      const content = fs.readFileSync(fullPath, "utf-8");
      const { data: rawData } = matter(content);
      try {
        const data = pageSchema.safeParse(rawData);
        if (!data.success) {
          throw new Error(z.prettifyError(data.error));
        }

        // const title = data.title || toPascalCaseSpace(fileName);
        // const description = data.metaSeoData?.description || title;

        const pageData = generatePageData(data.data);

        pages.push({
          url: `${BASE_URL}${normalizePathname(urlPath)}`,
          og: {
            imageUrl: `${BASE_URL}${normalizePathname(
              urlOgImage +
                normalizePathname(SOURCE_CONFIG.LOADER.OG.IMAGE_NAME, {
                  ignoreDomainExtensions: [".png"]
                })
            )}`
          },
          pageData
        });
      } catch (error) {
        if (error instanceof ZodError) {
          console.error(z.treeifyError(error).errors);
        } else {
          console.error(error);
        }
      }
    }
  }

  return pages;
}

const docsPages = getAllDocsPages(DOCS_DATA);

// Generate JSON-LD structured data
const structuredData = docsPages.map((page) => {
  return {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    headline: `${page.pageData.metaSeoData.title} | ${env.NEXT_PUBLIC_APP_NAME}`,
    description: page.pageData.metaSeoData.description,
    url: page.url,
    image: page.og.imageUrl,
    publisher: {
      "@type": "Organization",
      name: "Rzl Zone",
      url: BASE_URL
    }
    // datePublished: new Date().toISOString(),
    // dateModified: new Date().toISOString()
  } satisfies CachedJsonLD;
});

const outputPath = path.join(process.cwd(), "data/cache/jsonLD.ts");
ensureParentDir(outputPath);

const tsContent = `/** ----------------------------------------------------
 * * ***DO NOT EDIT MANUALLY !!!***
 * ----------------------------------------------------
 * ***Auto-generated by \`generate-json_ld-docs.ts\` or \`npm run generate:json_ld-docs\`.***
 */
export const cacheJsonLD = ${JSON.stringify(structuredData, null, 2)};
`;

fs.writeFileSync(outputPath, tsContent);

console.log("✅ Structured Data JSON-LD generated!");
console.log("   ➤ ", outputPath);
