
/** ----------------------------------------------------
 * * ***DO NOT EDIT MANUALLY !!!***
 * ----------------------------------------------------
 * ***Auto-generated by `generate-docs-cache.ts` or `npm run generate:docs-cache`.***
 */
export const cacheDocsPackage = [
  {
    "key": "build-tools",
    "slug": "build-tools",
    "name": "Build Tools",
    "description": "Build tools Rzl Zone.",
    "versions": [
      "latest"
    ],
    "githubUrl": "https://github.com/rzl-zone/rzl-zone/tree/main/packages/build-tools",
    "actualVersionLatest": {
      "latest": "0.0.7"
    }
  },
  {
    "key": "utils-js",
    "slug": "utils-js",
    "name": "UtilsJS",
    "description": "Utility Packages JS/TS.",
    "versions": [
      "latest"
    ],
    "githubUrl": "https://github.com/rzl-zone/rzl-zone/tree/main/packages/utils-js",
    "actualVersionLatest": {
      "2": "2.25.10",
      "latest": "3.11.0"
    }
  }
];
