/** ----------------------------------------------------
 * * ***DO NOT EDIT MANUALLY !!!***
 * ----------------------------------------------------
 * ***Auto-generated by `generate-json_ld-docs.ts` or `npm run generate:json_ld-docs`.***
 */
export const cacheJsonLD = [
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Code of Conduct - Build Tools | Rzl Zone",
    "description": "Code of Conduct outlining community standards and expectations for contributors to Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/code-of-conduct",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/code-of-conduct/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Contributing - Build Tools | Rzl Zone",
    "description": "Contribution guidelines for contributors and maintainers of Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/contributing",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/contributing/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "License - Build Tools | Rzl Zone",
    "description": "MIT License details and usage terms for Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/license",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/license/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Security Policy - Build Tools | Rzl Zone",
    "description": "Security guidelines, best practices, and vulnerability reporting for Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/security",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/security/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Clean: cleanJsBuildArtifacts - Build Tools | Rzl Zone",
    "description": "Learn how the cleanJsBuildArtifacts utility in Build Tools by Rzl Zone removes build artifact comments from compiled JavaScript files to produce clean output.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/clean/clean-js-build-artifacts",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/clean/clean-js-build-artifacts/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Clean: cleanTypesBuildArtifacts - Build Tools | Rzl Zone",
    "description": "Learn how the cleanTypesBuildArtifacts utility in Build Tools by Rzl Zone removes build artifact comments from TypeScript declaration files (.d.ts, .d.mts, .d.cts) to produce clean output.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/clean/clean-ts-build-artifacts",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/clean/clean-ts-build-artifacts/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Copy: copyFileToDest - Build Tools | Rzl Zone",
    "description": "Learn how the copyFileToDest utility in Build Tools by Rzl Zone copies assets such as CSS, JavaScript, JSON, images, fonts, and other static files into your build output directories.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/copy/copy-file-to-dest",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/copy/copy-file-to-dest/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Ensure: ensureCssImport - Build Tools | Rzl Zone",
    "description": "Learn how the ensureCssImport utility in Build Tools by Rzl Zone ensures CSS imports exist in compiled JavaScript files with optional deduplication and sorting.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/ensure/ensure-css-import",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/ensure/ensure-css-import/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Ensure: ensureFinalNewline - Build Tools | Rzl Zone",
    "description": "Learn how the ensureFinalNewline utility in Build Tools by Rzl Zone ensures matched files end with exactly one final newline while preserving internal formatting.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/ensure/ensure-final-newline",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/ensure/ensure-final-newline/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Generate: generatePackageBanner - Build Tools | Rzl Zone",
    "description": "Learn how the generatePackageBanner utility in Build Tools by Rzl Zone creates standardized banner comments from package.json metadata for build and distribution outputs.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/generate/generate-package-banner",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/generate/generate-package-banner/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Generate: generateReferenceIndex - Build Tools | Rzl Zone",
    "description": "Learn how the generateReferenceIndex utility in Build Tools by Rzl Zone generates a TypeScript declaration reference index file from matched output files with optional exports.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/generate/generate-reference-index",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/generate/generate-reference-index/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Get: getPackageJson - Build Tools | Rzl Zone",
    "description": "Learn how the getPackageJson utility in Build Tools by Rzl Zone resolves and reads the nearest package.json for build tools, bundlers, CLI utilities, and monorepo-aware infrastructure code.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/get/get-package-json",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/get/get-package-json/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Installation - Build Tools | Rzl Zone",
    "description": "Installation instructions for Build Tools (latest version) by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/installation",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/installation/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Requirements - Build Tools | Rzl Zone",
    "description": "Requirements for Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/requirements",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/requirements/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Documentation2 - Build Tools 2 | Rzl Zone",
    "description": "Modern build tools for the Rzl Zone ecosystem, providing TypeScript-first workflows and bundling utilities for scalable JavaScript projects2.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/main-index",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/main-index/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Changelog - Build Tools | Rzl Zone",
    "description": "Complete changelog and release history for Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/changelog",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/changelog/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Documentation - Build Tools | Rzl Zone",
    "description": "Modern build tools for the Rzl Zone ecosystem, providing TypeScript-first workflows and bundling utilities for scalable JavaScript projects.",
    "url": "https://rzlzone.vercel.app/docs/build-tools",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Rzl Zone Docs | Rzl Zone",
    "description": "Official documentation for Rzl Zone, providing detailed guides, utilities, and API references.",
    "url": "https://rzlzone.vercel.app/docs",
    "image": "https://rzlzone.vercel.app/og/docs/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Assertion: assertIsArray - UtilsJS | Rzl Zone",
    "description": "Learn how the assertIsArray utility in UtilsJS version 3 by Rzl Zone provides strict array type assertions for JavaScript and TypeScript.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/assertions/assert-is-array",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/assertions/assert-is-array/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "CDN Usage - UtilsJS | Rzl Zone",
    "description": "How to use UtilsJS via CDN safely in the browser by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/cdn-usage",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/cdn-usage/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Installation - UtilsJS | Rzl Zone",
    "description": "Installation instructions for UtilsJS version 3 by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/installation",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/installation/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Requirements - UtilsJS | Rzl Zone",
    "description": "Requirements for UtilsJS version 3 by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/requirements",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/requirements/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Changelog - UtilsJS | Rzl Zone",
    "description": "Complete changelog and release history for UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/changelog",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/changelog/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Code of Conduct - UtilsJS | Rzl Zone",
    "description": "Code of Conduct outlining community standards and expectations for contributors to UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/code-of-conduct",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/code-of-conduct/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Contributing - UtilsJS | Rzl Zone",
    "description": "Contribution guidelines for contributors and maintainers of UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/contributing",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/contributing/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Documentation - UtilsJS | Rzl Zone",
    "description": "Lightweight utility library for TypeScript and JavaScript with reusable, type-safe helpers for Node.js and browsers — built by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "License - UtilsJS | Rzl Zone",
    "description": "MIT License details and usage terms for UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/license",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/license/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Security Policy - UtilsJS | Rzl Zone",
    "description": "Security guidelines, best practices, and vulnerability reporting for UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/security",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/security/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  }
];
