/** ----------------------------------------------------
 * * ***DO NOT EDIT MANUALLY !!!***
 * ----------------------------------------------------
 * ***Auto-generated by `generate-json_ld-docs.ts` or `npm run generate:json_ld-docs`.***
 */
export const cacheJsonLD = [
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Code of Conduct - Build Tools | Rzl Zone",
    "description": "Code of Conduct outlining community standards and expectations for contributors to Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/code-of-conduct",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/code-of-conduct/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Contributing - Build Tools | Rzl Zone",
    "description": "Contribution guidelines for contributors and maintainers of Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/contributing",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/contributing/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "License - Build Tools | Rzl Zone",
    "description": "MIT License details and usage terms for Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/license",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/license/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Security Policy - Build Tools | Rzl Zone",
    "description": "Security guidelines, best practices, and vulnerability reporting for Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/security",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/security/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Cleaner: cleanJsBuildArtifacts - Build Tools | Rzl Zone",
    "description": "Learn how the cleanJsBuildArtifacts utility in Build Tools by Rzl Zone removes build artifact comments from compiled JavaScript files to produce cleaner output.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/cleaner/clean-js-build-artifacts",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/cleaner/clean-js-build-artifacts/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Cleaner: cleanTypesBuildArtifacts - Build Tools | Rzl Zone",
    "description": "Learn how the cleanTypesBuildArtifacts utility in Build Tools by Rzl Zone removes build artifact comments from TypeScript declaration files (.d.ts, .d.mts, .d.cts) to produce cleaner output.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/cleaner/clean-ts-build-artifacts",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/cleaner/clean-ts-build-artifacts/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Installation - Build Tools | Rzl Zone",
    "description": "Installation instructions for Build Tools (latest version) by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/installation",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/installation/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Requirements - Build Tools | Rzl Zone",
    "description": "Requirements for Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/requirements",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/requirements/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Documentation2 - Build Tools 2 | Rzl Zone",
    "description": "Modern build tools for the Rzl Zone ecosystem, providing TypeScript-first workflows and bundling utilities for scalable JavaScript projects2.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/main-index",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/main-index/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Changelog - Build Tools | Rzl Zone",
    "description": "Complete changelog and release history for Build Tools by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/build-tools/changelog",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/changelog/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Documentation - Build Tools | Rzl Zone",
    "description": "Modern build tools for the Rzl Zone ecosystem, providing TypeScript-first workflows and bundling utilities for scalable JavaScript projects.",
    "url": "https://rzlzone.vercel.app/docs/build-tools",
    "image": "https://rzlzone.vercel.app/og/docs/build-tools/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Rzl Zone Docs | Rzl Zone",
    "description": "Official documentation for Rzl Zone, providing detailed guides, utilities, and API references.",
    "url": "https://rzlzone.vercel.app/docs",
    "image": "https://rzlzone.vercel.app/og/docs/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Assertion: assertIsArray - UtilsJS | Rzl Zone",
    "description": "Learn how the assertIsArray utility in UtilsJS version 3 by Rzl Zone provides strict array type assertions for JavaScript and TypeScript.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/assertions/assert-is-array",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/assertions/assert-is-array/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "CDN Usage - UtilsJS | Rzl Zone",
    "description": "How to use UtilsJS via CDN safely in the browser by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/cdn-usage",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/cdn-usage/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Installation - UtilsJS | Rzl Zone",
    "description": "Installation instructions for UtilsJS version 3 by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/installation",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/installation/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Requirements - UtilsJS | Rzl Zone",
    "description": "Requirements for UtilsJS version 3 by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/requirements",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/requirements/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Changelog - UtilsJS | Rzl Zone",
    "description": "Complete changelog and release history for UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/changelog",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/changelog/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Code of Conduct - UtilsJS | Rzl Zone",
    "description": "Code of Conduct outlining community standards and expectations for contributors to UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/code-of-conduct",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/code-of-conduct/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Contributing - UtilsJS | Rzl Zone",
    "description": "Contribution guidelines for contributors and maintainers of UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/contributing",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/contributing/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Documentation - UtilsJS | Rzl Zone",
    "description": "Lightweight utility library for TypeScript and JavaScript with reusable, type-safe helpers for Node.js and browsers — built by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "License - UtilsJS | Rzl Zone",
    "description": "MIT License details and usage terms for UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/license",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/license/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  },
  {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    "headline": "Security Policy - UtilsJS | Rzl Zone",
    "description": "Security guidelines, best practices, and vulnerability reporting for UtilsJS by Rzl Zone.",
    "url": "https://rzlzone.vercel.app/docs/utils-js/security",
    "image": "https://rzlzone.vercel.app/og/docs/utils-js/security/image.png",
    "publisher": {
      "@type": "Organization",
      "name": "Rzl Zone",
      "url": "https://rzlzone.vercel.app"
    }
  }
];
