import { Command } from "commander";

import { isNonEmptyString } from "@/_internal/utils/helper";

/** ----------------------------------------------------------------
 * * ***CLI command definition class.***
 * ----------------------------------------------------------------
 *
 * Primary building block used to define CLI programs and
 * subcommands.
 *
 * This class extends Commander’s {@link Command | **`Command`**} class and
 * adds additional behavior and type safety used by
 * this library.
 *
 * Importing this class from this module ensures that
 * the additional type definitions and helpers provided
 * by this library are available.
 *
 * ----------------------------------------------------------------
 *
 * @example
 * ```ts
 * import { CliCommand } from "@rzl-zone/build-tools/commander-kit";
 *
 * const program = new CliCommand();
 *
 * program
 *   .name("my-cli")
 *   .description("Example CLI program");
 *
 * program.parse();
 * ```
 */
export class CliCommand extends Command {
  /** ----------------------------------------------------------------
   * * ***Create a new CLI command instance.***
   * ----------------------------------------------------------------
   *
   * @param name Optional command name.
   *
   * If the provided value is not a non-empty string,
   * the command will be created without an explicit name.
   */
  constructor(name?: string) {
    name = isNonEmptyString(name) ? name : undefined;
    super(name);
  }

  /** Set or disable the command usage string.
   *
   * This overrides the default usage generated from the command
   * metadata (such as the command name, arguments, and options).
   *
   * - Passing a **non-empty string** sets a custom usage value.
   * - Passing **`false`** disables usage output entirely for this
   *   command (including help and error rendering when supported
   *   by the CLI framework integration).
   *
   * An **empty string is not allowed** and will cause a configuration
   * error to be thrown.
   *
   * @param str A non-empty custom usage string, or `false`
   * to disable usage output.
   *
   * @returns The current command instance for chaining.
   *
   * @throws Thrown if the provided usage value is an empty string or
   * not a valid non-empty string.
   *
   * @example
   * program.usage("build [options]");
   *
   * @example
   * program.usage(false);
   */
  override usage(str: string | false): this;
  /** Get the resolved command usage string.
   *
   * If a custom usage was previously set using {@link Command.usage | `usage`},
   * that value will be returned. Otherwise the usage string
   * generated by Commander will be returned.
   *
   * @returns The current usage string for this command.
   */
  override usage(): string;
  override usage(str?: string | false): this | string {
    if (str === false) {
      super.usage("");
      return this;
    }

    if (!isNonEmptyString(str)) {
      return super.usage();
    }

    return super.usage(str);
  }

  /** Set or disable the program version.
   *
   * This method configures the version value for the CLI program and
   * automatically registers the `"-v, --version"` flag which prints
   * the version when invoked.
   *
   * Behavior depends on the value passed:
   *
   * - Passing a **non-empty string** sets the program version.
   * - Passing **`false`** disables the version flag entirely.
   *
   * When providing custom `flags` or `description`, they must also be
   * **non-empty strings**.
   *
   * An **empty string is not allowed** and will cause a configuration
   * error to be thrown.
   *
   * @param str A non-empty version string, or `false` to disable
   * the version flag.
   *
   * @param flags Optional custom version flags (e.g. `"-V, --version"`).
   *
   * @param description Optional description for the version flag.
   *
   * @returns The current program instance for chaining.
   *
   * @throws Thrown if `str`, `flags`, or `description` are provided
   * as empty strings or invalid values.
   *
   * @example
   * program.version("1.0.0");
   *
   * @example
   * program.version("1.0.0", "-V, --version", "print version");
   *
   * @example
   * program.version(false);
   */
  override version(str: string, flags?: string, description?: string): this;
  /** Set or disable the program version.
   *
   * This method configures the version value for the CLI program and
   * automatically registers the `"-v, --version"` flag which prints
   * the version when invoked.
   *
   * Behavior depends on the value passed:
   *
   * - Passing a **non-empty string** sets the program version.
   * - Passing **`false`** disables the version flag entirely.
   *
   * When providing custom `flags` or `description`, they must also be
   * **non-empty strings**.
   *
   * An **empty string is not allowed** and will cause a configuration
   * error to be thrown.
   *
   * @param str A non-empty version string, or `false` to disable
   * the version flag.
   *
   * @param flags Optional custom version flags (e.g. `"-V, --version"`).
   *
   * @param description Optional description for the version flag.
   *
   * @returns The current program instance for chaining.
   *
   * @throws Thrown if `str`, `flags`, or `description` are provided
   * as empty strings or invalid values.
   *
   * @example
   * program.version("1.0.0");
   *
   * @example
   * program.version("1.0.0", "-V, --version", "print version");
   *
   * @example
   * program.version(false);
   */
  override version(str: false): this;
  /** Set or disable the program version.
   *
   * This method configures the version value for the CLI program and
   * automatically registers the `"-v, --version"` flag which prints
   * the version when invoked.
   *
   * Behavior depends on the value passed:
   *
   * - Passing a **non-empty string** sets the program version.
   * - Passing **`false`** disables the version flag entirely.
   *
   * When providing custom `flags` or `description`, they must also be
   * **non-empty strings**.
   *
   * An **empty string is not allowed** and will cause a configuration
   * error to be thrown.
   *
   * @param str A non-empty version string, or `false` to disable
   * the version flag.
   *
   * @param flags Optional custom version flags (e.g. `"-V, --version"`).
   *
   * @param description Optional description for the version flag.
   *
   * @returns The current program instance for chaining.
   *
   * @throws Thrown if `str`, `flags`, or `description` are provided
   * as empty strings or invalid values.
   *
   * @example
   * program.version("1.0.0");
   *
   * @example
   * program.version("1.0.0", "-V, --version", "print version");
   *
   * @example
   * program.version(false);
   */
  override version(str: false, flags?: never): this;
  /** Set or disable the program version.
   *
   * This method configures the version value for the CLI program and
   * automatically registers the `"-v, --version"` flag which prints
   * the version when invoked.
   *
   * Behavior depends on the value passed:
   *
   * - Passing a **non-empty string** sets the program version.
   * - Passing **`false`** disables the version flag entirely.
   *
   * When providing custom `flags` or `description`, they must also be
   * **non-empty strings**.
   *
   * An **empty string is not allowed** and will cause a configuration
   * error to be thrown.
   *
   * @param str A non-empty version string, or `false` to disable
   * the version flag.
   *
   * @param flags Optional custom version flags (e.g. `"-V, --version"`).
   *
   * @param description Optional description for the version flag.
   *
   * @returns The current program instance for chaining.
   *
   * @throws Thrown if `str`, `flags`, or `description` are provided
   * as empty strings or invalid values.
   *
   * @example
   * program.version("1.0.0");
   *
   * @example
   * program.version("1.0.0", "-V, --version", "print version");
   *
   * @example
   * program.version(false);
   */
  override version(str: false, flags?: never, description?: never): this;
  /** Get the program version.
   *
   * Returns the currently configured version string.
   *
   * If the version was disabled using {@link Command.version | `version(false)`},
   * this method returns `undefined`.
   *
   * @returns The current program version string if set.
   */
  override version(): string | undefined;
  override version(str?: string | false, flags?: string, description?: string) {
    if (str === false) {
      super.version("");
      return this;
    }

    if (!isNonEmptyString(str)) {
      return super.version();
    }

    return super.version(str, flags, description);
  }
}
